[package]
name = "wc"
version = "0.1.0"
authors = ["palash25 <npalash25@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.31.2"
ansi_term = "0.12.1"
